import type {
  Admin,
  Assignment,
  Class,
  Grade,
  Notification,
  Student,
  Subject,
  Teacher,
} from "./types";

// Mock Students
export const mockStudents: Student[] = [
  {
    id: "student-1",
    email: "harshit@gmail.com",
    password: "password123",
    role: "student",
    firstName: "Harshit",
    lastName: "Mishra",
    phone: "555-0101",
    studentId: "STU001",
    grade: 10,
    gradeLevel: "10th Grade", // ✅ added
    section: "A",
    dateOfBirth: new Date("2008-05-15"),
    address: "Swaroop Nagar, City, State",
    enrollmentDate: new Date("2023-09-01"),
    status: "active",
    createdAt: new Date("2023-08-15"),
    updatedAt: new Date("2023-08-15"),
  },
  {
    id: "student-2",
    email: "Diyasrivastava@gmail.com",
    password: "password123",
    role: "student",
    firstName: "Diya",
    lastName: "Srivastava",
    phone: "",
    studentId: "STU002",
    grade: 10,
    gradeLevel: "10th Grade", // ✅ added
    section: "A",
    dateOfBirth: new Date("2008-03-22"),
    address: "swaroop nagar, City, State",
    enrollmentDate: new Date("2023-09-01"),
    status: "active",
    createdAt: new Date("2023-08-15"),
    updatedAt: new Date("2023-08-15"),
  },
  {
    id: "student-3",
    email: "kaur@gmail.com",
    password: "password123",
    role: "student",
    firstName: "kaur",
    lastName: "kaur",
    phone: "555-0103",
    studentId: "STU003",
    grade: 11,
    gradeLevel: "11th Grade", // ✅ added
    section: "B",
    dateOfBirth: new Date("2007-11-08"),
    address: "Bhauti, City, State",
    enrollmentDate: new Date("2022-09-01"),
    status: "active",
    createdAt: new Date("2022-08-15"),
    updatedAt: new Date("2022-08-15"),
  },
];

// Mock Teachers
export const mockTeachers: Teacher[] = [
  {
    id: "teacher-1",
    email: "santoshsir@gmail.com",
    password: "password123",
    role: "teacher",
    firstName: "santosh",
    lastName: "sir",
    phone: "555-0201",
    teacherId: "TCH001",
    department: "DS",
    subjects: ["Algebra", "Geometry", "Calculus"],
    qualification: "Phd DS",
    experience: 18,
    salary: 150000,
    joinDate: new Date("2020-08-15"),
    createdAt: new Date("2020-08-01"),
    updatedAt: new Date("2020-08-01"),
  },
  {
    id: "teacher-2",
    email: "faculty2@gmail.com",
    password: "password123",
    role: "teacher",
    firstName: "faculty",
    lastName: ".",
    phone: "",
    teacherId: "TCH002",
    department: "Science",
    subjects: ["Physics", "Chemistry"],
    qualification: "M.Sc Physics",
    experience: 12,
    salary: 70000,
    joinDate: new Date("2018-08-15"),
    createdAt: new Date("2018-08-01"),
    updatedAt: new Date("2018-08-01"),
  },
  {
    id: "teacher-3",
    email: "Shinchan",
    password: "password123",
    role: "teacher",
    firstName: "Shin",
    lastName: "Chan",
    phone: "555-0203",
    teacherId: "TCH003",
    department: "English",
    subjects: ["English Literature", "Creative Writing"],
    qualification: "M.A English",
    experience: 6,
    salary: 60000,
    joinDate: new Date("2021-08-15"),
    createdAt: new Date("2021-08-01"),
    updatedAt: new Date("2021-08-01"),
  },
];

// Mock Admin
export const mockAdmins: Admin[] = [
  {
    id: "admin-1",
    email: "Ayush@gmail.com",
    password: "admin123",
    role: "admin",
    firstName: "Ayush",
    lastName: "Kumar",
    phone: "555-0301",
    adminId: "ADM001",
    permissions: [
      "manage_users",
      "manage_courses",
      "view_reports",
      "manage_grades",
    ],
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-01-01"),
  },
];

// Mock Subjects
export const mockSubjects: Subject[] = [
  {
    id: "subject-1",
    name: "Algebra",
    code: "MATH101",
    description: "Introduction to algebraic concepts and problem solving",
    credits: 3,
    department: "Mathematics",
    grade: 10,
    isActive: true,
  },
  {
    id: "subject-2",
    name: "Physics",
    code: "PHYS101",
    description: "Fundamental principles of physics",
    credits: 4,
    department: "Science",
    grade: 10,
    isActive: true,
  },
  {
    id: "subject-3",
    name: "English Literature",
    code: "ENG101",
    description: "Study of classic and contemporary literature",
    credits: 3,
    department: "English",
    grade: 10,
    isActive: true,
  },
  {
    id: "subject-4",
    name: "Calculus",
    code: "MATH201",
    description: "Advanced calculus and mathematical analysis",
    credits: 4,
    department: "Mathematics",
    grade: 11,
    isActive: true,
  },
];

// Mock Classes
export const mockClasses: Class[] = [
  {
    id: "class-1",
    name: "Algebra - Grade 10A",
    grade: 10,
    section: "A",
    teacherId: "teacher-1",
    subjectId: "subject-1",
    schedule: [
      { dayOfWeek: 1, startTime: "09:00", endTime: "10:00", room: "Room 101" },
      { dayOfWeek: 3, startTime: "10:00", endTime: "11:00", room: "Room 101" },
      { dayOfWeek: 5, startTime: "11:00", endTime: "12:00", room: "Room 101" },
    ],
    maxStudents: 30,
    enrolledStudents: ["student-1", "student-2"],
    academicYear: "2023-2024",
  },
  {
    id: "class-2",
    name: "Physics - Grade 10A",
    grade: 10,
    section: "A",
    teacherId: "teacher-2",
    subjectId: "subject-2",
    schedule: [
      { dayOfWeek: 2, startTime: "09:00", endTime: "10:00", room: "Lab 201" },
      { dayOfWeek: 4, startTime: "14:00", endTime: "15:00", room: "Lab 201" },
    ],
    maxStudents: 25,
    enrolledStudents: ["student-1", "student-2"],
    academicYear: "2023-2024",
  },
];

// Mock Assignments
export const mockAssignments: Assignment[] = [
  {
    id: "assignment-1",
    title: "Quadratic Equations Practice",
    description: "Solve the given quadratic equations using different methods",
    subjectId: "subject-1",
    teacherId: "teacher-1",
    classId: "class-1",
    dueDate: new Date("2024-02-15"),
    maxMarks: 100,
    type: "homework",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "assignment-2",
    title: "Physics Lab Report",
    description: "Write a detailed report on the pendulum experiment",
    subjectId: "subject-2",
    teacherId: "teacher-2",
    classId: "class-2",
    dueDate: new Date("2024-02-20"),
    maxMarks: 50,
    type: "project",
    createdAt: new Date("2024-02-05"),
  },
];

// Mock Grades
export const mockGrades: Grade[] = [
  {
    id: "grade-1",
    studentId: "student-1",
    assignmentId: "assignment-1",
    marksObtained: 85,
    maxMarks: 100,
    percentage: 85,
    grade: "A",
    feedback: "Excellent work! Good understanding of concepts.",
    submittedAt: new Date("2024-02-14"),
    gradedAt: new Date("2024-02-16"),
    gradedBy: "teacher-1",
  },
  {
    id: "grade-2",
    studentId: "student-2",
    assignmentId: "assignment-1",
    marksObtained: 78,
    maxMarks: 100,
    percentage: 78,
    grade: "B+",
    feedback: "Good work, but needs improvement in problem-solving approach.",
    submittedAt: new Date("2024-02-15"),
    gradedAt: new Date("2024-02-17"),
    gradedBy: "teacher-1",
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    recipientId: "student-1",
    recipientType: "student",
    title: "New Assignment Posted",
    message: "A new assignment has been posted for Algebra class.",
    type: "assignment",
    isRead: false,
    createdAt: new Date("2024-02-01"),
    createdBy: "teacher-1",
  },
  {
    id: "notif-2",
    recipientId: "student-1",
    recipientType: "student",
    title: "Grade Updated",
    message: "Your grade for Quadratic Equations Practice has been updated.",
    type: "grade",
    isRead: false,
    createdAt: new Date("2024-02-16"),
    createdBy: "teacher-1",
  },
];
